redfin:
  base_url: https://www.redfin.com/stingray/do/location-autocomplete
  user_agent: ${USER_AGENT}
home_pulse_ai_db:
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  user: ${MYSQL_USER}
  password: ${MYSQL_PASS}
  db:  ${MYSQL_DB}
security:
  secret_key: ${SECRET_KEY}
stripe:
  secret_key: ${STRIPE_SECRET_KEY}
  success_url: https://dannyjosephgarcia.github.io/Home-Pulse-AI-V1.0/#/success?session_id={CHECKOUT_SESSION_ID}
  cancel_url: https://dannyjosephgarcia.github.io/Home-Pulse-AI-V1.0/#/cancel
  mode: subscription
  payment_type: card
  price: price_1RsmlK2R3IIW0X0zwLIylvjr
  webhook_secret: ${STRIPE_WEBHOOK_SECRET}
