redfin:
  base_url: https://www.redfin.com/stingray/do/location-autocomplete
  user_agent: ${USER_AGENT}
home_pulse_ai_db:
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  user: ${MYSQL_USER}
  password: ${MYSQL_PASS}
  db:  ${MYSQL_DB}
security:
  secret_key: ${SECRET_KEY}
